-- Database First

CREATE DATABASE LojinhaDb;

GO
USE LojinhaDb;
GO

CREATE TABLE TypeUsers(
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name nvarchar(50) NOT NULL
);

CREATE TABLE Users(
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name nvarchar(100) NOT NULL,
	Email nvarchar(100) UNIQUE NOT NULL,
	TypeUserId BIGINT NOT NULL FOREIGN KEY REFERENCES TypeUsers(Id)
);

CREATE TABLE Products(
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name nvarchar(100) NOT NULL
);

CREATE TABLE Orders(
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	UserId BIGINT NOT NULL FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE OrderProducts(
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	OrderId BIGINT NOT NULL FOREIGN KEY REFERENCES Orders(Id) ON DELETE CASCADE,
	ProductId BIGINT NOT NULL FOREIGN KEY REFERENCES Products(Id)
);